thermos/models.py
from datetime import datetime

from sqlalchemy import desc  # descending order
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from thermos import db


# setup junction table
tags = db.Table('bookmark_tag',
                db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),
                db.Column('bookmark_id', db.Integer, db.ForeignKey('bookmark.id'))
                )

class Bookmark(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.Text, nullable=False)
    date = db.Column(db.DateTime, default=datetime.utcnow)
    description = db.Column(db.String(300))
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)
    _tags = db.relationship('Tag',
                            secondary=tags, lazy="dynamic",
                            backref=db.backref('bookmarks', lazy='dynamic'))

    @staticmethod
    def newest(num):
        return Bookmark.query.order_by(desc(Bookmark.date)).limit(num)

    @property
    def tags(self):
        return ",".join([t.name for t in self._tags])

    @tags.setter
    def tags(self, string):
        if string:
            self._tags = [Tag.get_or_create(name) for name in string.split(',')]
        else:
            self._tags = []
    
    def __repr__(self):
        return "<Bookmark '{}': '{}'>".format(self.description, self.url)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)
    bookmarks = db.relationship('Bookmark', backref='user', lazy='dynamic')
    password_hash = db.Column(db.String)

    @property
    def password(self):
        raise AttributeError('password: write-only field')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    @staticmethod
    def get_by_username(username):
        return User.query.filter_by(username=username).first()

    def __repr__(self):
        return "<User '{}'>".format(self.username)

class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(25), nullable=False, unique=True, index=True)

    @staticmethod
    def get_or_create(name):
        try:
            return Tag.query.filter_by(name=name).one()
        except:
            return Tag(name=name)

    @staticmethod
    def all():
        return Tag.query.all()

    def __repr__(self):
        return self.name

thermos/bookmarks/forms.py
from flask_wtf import Form
from wtforms.fields import StringField
from wtforms.fields.html5 import URLField
from wtforms.validators import DataRequired, Regexp, url


class BookmarkForm(Form):
    url = URLField('The URL for your bookmark', validators=[DataRequired(), url()])
    description = StringField('Add an optional description:')
    tags = StringField('Tags', validators=[Regexp(r'^[a-zA-Z0-9, ]*$',
                    message="Tags can only contain letters and numbers")])

    def validate(self):
        if not self.url.data.startswith('http://') or\
            self.url.data.startswith('https://'):
            self.url.data = "http://" + self.url.data

        if not Form.validate(self):
            return False

        if not self.description.data:
            self.description.data = self.url.data

        # filter out empty and duplicate tag names
        stripped = [t.strip() for t in self.tags.data.split(',')]  # strip all white space
        not_empty = [tag for tag in stripped if tag]  # remove all empty string
        tagset = set(not_empty)  # remove duplicate using set
        self.tags.data = ",".join(tagset)

        return True

thermos/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, PasswordField, BooleanField, SubmitField
from wtforms.fields.html5 import URLField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo, url, ValidationError
from thermos.models import User

class BookmarkForm(Form):
    url = URLField('The URL for your bookmark', validators=[DataRequired(), url()])
    description = StringField('Add an optional description:')
    tags = StringField('Tags', validators=[Regexp(r'^[a-zA-Z0-9, ]*$',
                    message="Tags can only contain letters and numbers")])

    def validate(self):
        if not self.url.data.startswith('http://') or\
            self.url.data.startswith('https://'):
            self.url.data = "http://" + self.url.data

        if not Form.validate(self):
            return False

        if not self.description.data:
            self.description.data = self.url.data

        # filter out empty and duplicate tag names
        stripped = [t.strip() for t in self.tags.data.split(',')]  # strip all white space
        not_empty = [tag for tag in stripped if tag]  # remove all empty string
        tagset = set(not_empty)  # remove duplicate using set
        self.tags.data = ",".join(tagset)

        return True

class LoginForm(Form):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Keep me logged in')
    submit = SubmitField('Sign In')

class SignupForm(Form):
    username = StringField('Username',
                           validators=[
                               DataRequired(),
                               Length(3, 80),
                               Regexp('^[A-Za-z0-9_]{3,}$',
                                      message="Username consist of numbers, letters and underscores.")])
    password = PasswordField('Password',
                             validators=[
                                 DataRequired(),
                                 EqualTo('password2',
                                         message="Password must match.")])
    password2 = PasswordField('Confirm password', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Length(1, 120), Email()])

    def validate_email(self, email_field):
        if User.query.filter_by(email=email_field.data).first():
            raise ValidationError("There already is a user with this email address.")

    def validate_username(self, username_field):
        if User.query.filter_by(username=username_field.data).first():
            raise ValidationError("This Username is already taken.")

thermos/__init__.py
import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_moment import Moment
from flask_debugtoolbar import DebugToolbarExtension

from .config import config_by_name

db = SQLAlchemy()

# Configure authentication
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

# Flask Debug Toolbar
toolbar = DebugToolbarExtension()

# for displaying timestamps
moment = Moment()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_by_name[config_name])
    db.init_app(app)
    login_manager.init_app(app)  # Authentication
    moment.init_app(app)  # Date and time lib
    toolbar.init_app(app)  # Debug Toolbar

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint, url_prefix='/')

    from .bookmarks import bookmarks as bkm_blueprint
    app.register_blueprint(bkm_blueprint, url_prefix='/bookmarks')

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

thermos/bookmarks/__init__.py
from flask import Blueprint

bookmarks = Blueprint('bookmarks', __name__)

from . import views

thermos/bookmarks/views.py
from flask import render_template, flash, redirect, url_for, request, abort
from flask_login import login_required, current_user

from . import bookmarks
from .forms import BookmarkForm
from .. import db
from ..models import User, Bookmark, Tag

@bookmarks.route('/add', methods=['GET','POST'])
@login_required
def add():
    form = BookmarkForm()
    if form.validate_on_submit():
        url = form.url.data
        description = form.description.data
        tags = form.tags.data
        bm = Bookmark(user=current_user, url=url, description=description, tags=tags)
        db.session.add(bm)
        db.session.commit()
        flash("stored url: '{}'".format(description))
        return redirect(url_for('main.index'))
    return render_template('add.html', form=form)

@bookmarks.route('/edit/<int:bookmark_id>', methods=['GET','POST'])
@login_required
def edit_bookmark(bookmark_id):
    bookmark = Bookmark.query.get_or_404(bookmark_id)
    if current_user != bookmark.user:
        abort(403)
    form = BookmarkForm(obj=bookmark)
    if form.validate_on_submit():
        form.populate_obj(bookmark)  # copy data from form to bookmark obj
        db.session.commit()
        flash("Stored '{}'".format(bookmark.description))
        return redirect(url_for('.user', username=current_user.username))
    return render_template('bookmark_form.html', form=form, title="Edit bookmark")

@bookmarks.route('/delete/<int:bookmark_id>', methods=['GET','POST'])
@login_required
def delete_bookmark(bookmark_id):
    bookmark = Bookmark.query.get_or_404(bookmark_id)
    if current_user != bookmark.user:
        abort(403)
    if request.method == 'POST':
        db.session.delete(bookmark)
        db.session.commit()
        flash("Deleted '{}'".format(bookmark.description))
        return redirect(url_for('.user', username=current_user.username))
    else:
        flash("Please confirm deleting the bookmark.")
    return render_template('confirm_delete.html', bookmark=bookmark, nolinks=True)

@bookmarks.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user.html', user=user)

@bookmarks.route('/tag/<name>')
def tag(name):
    tag = Tag.query.filter_by(name=name).first_or_404()
    return render_template('tag.html', tag=tag)

thermos/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

thermos/main/views.py
from flask import render_template

from . import main
from .. import login_manager
from ..models import User, Bookmark, Tag


@login_manager.user_loader
def load_user(userid):
    return User.query.get(int(userid))

@main.route("/")
def index():
    return render_template('index.html', new_bookmarks=Bookmark.newest(5))

@main.app_errorhandler(403)
def forbidden(e):
    return render_template('403.html'), 403

@main.app_errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

@main.app_errorhandler(500)
def server_error(e):
    return render_template('500.html'), 500

"""app.context_processor
- make sth globally accessible in the template context
- method with this decorator will be executed every time before a template is rendered.
"""
@main.app_context_processor  #
def inject_tags():
    return dict(all_tags=Tag.all)

thermos/templates/add.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Add bookmark
{% endblock %}

{% block content %}
<section>
    <h1>Add a new URL</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <table>
            {{ render_field(form.url, size=50) }}
            {{ render_field(form.description, size=50) }}
            <tr>
                <td></td>
                <td><button type="submit">Submit</button></td>
            </tr>
        </table>
    </form>
</section>
{% endblock %}

{% block sidebar %}
{% endblock %}

thermos/templates/base.html
<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% block styles %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        {% endblock %}

        <script src="{{ url_for('static', filename='js/vendor/modernizr-2.6.2-respond-1.1.0.min.js') }}"></script>
    </head>
    <body>

        <div class="header-container">
            <header class="wrapper clearfix">
                <a href="{{ url_for('main.index') }}"><h1 class="title">Thermos</h1></a>
                <nav>
                    <ul>
                        <li><a href="{{ url_for('bookmarks.add') }}">Add URL</a></li>
                        {% if current_user.is_authenticated %}
                            <li><a href="{{ url_for('bookmarks.user', username=current_user.username) }}">
                                My Links</a></li>
                            <li><a href="{{ url_for('auth.logout') }}">Sign out</a></li>
                        {% else %}
                            <li><a href="{{ url_for('auth.signup') }}">Sign up</a></li>
                            <li><a href="{{ url_for('auth.login') }}">Sign in</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </header>
        </div>

        <div class="main-container">
            <div class="main wrapper clearfix">
                <article class="flashes">
                    {% with messages = get_flashed_messages() %}
                      {% if messages %}
                        <ul>
                        {% for message in messages %}
                          <li>{{ message }}</li>
                        {% endfor %}
                        </ul>
                      {% endif %}
                    {% endwith %}
                </article>

                {%  block content %}
                {%  endblock %}

                {% block sidebar %}
                    <aside>
                        <h3>Tags</h3>
                            {% for t in all_tags() %}
                                <a href="{{ url_for('bookmarks.tag', name=t) }}">{{ t }}</a>
                            {% endfor %}
                    </aside>
                {% endblock %}
            </div> <!-- #main -->
        </div> <!-- #main-container -->

        <div class="footer-container">
            <footer class="wrapper">
                <p>Thermos by <a href="http://www.rjekker.nl">Reindert-Jan Ekker</a> for <a href="http://www.pluralsight.com">Pluralsight</a></p>
            </footer>
        </div>

        {{ moment.include_jquery() }}
        {{ moment.include_moment() }}

        {% block scripts %}
        {% endblock %}
    </body>
</html>

thermos/templates/bookmark.html
 <div class="bookmark">
    <a class="header" href="{{ bookmark.url }}">
        <h3 class="description">
            {{ bookmark.description|truncate(50, killwords=True) }}
        </h3>
        <span class="url">
            {{ bookmark.url|truncate(50, killwords=True) }}
        </span>
    </a>
    <div class="info">
        <span class="tags">
                {% if bookmark.tags %}
                    {% for t in bookmark._tags %}<a href="{{ url_for('bookmarks.tag', name=t.name) }}">{{ t }}</a>
                {% endfor %}
                {% else %}No tags.
                {% endif %}
        </span>
        <br>
        Added by <a href="{{ url_for('bookmarks.user', username=bookmark.user.username) }}">
            {{ bookmark.user.username }}
        </a>
        {{ moment(bookmark.date).fromNow() }}.
        {% if current_user == bookmark.user and not nolinks %}
            <span class="editlinks">
                <a href="{{ url_for('bookmarks.edit_bookmark', bookmark_id=bookmark.id) }}">edit</a>
                <a href="{{ url_for('bookmarks.delete_bookmark', bookmark_id=bookmark.id) }}">delete</a>
            </span>
        {% endif %}
    </div>
</div>

thermos/templates/bookmark_form.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/select2.css') }}">
{% endblock %}

{% block title %}
Thermos -- {{ title }}
{%  endblock %}

{% block content %}
    <section>
        <h1>{{ title }}</h1>
        <form action="" method="post">
            {{form.hidden_tag()}}
            <table>
                {{ render_field(form.url, size=50) }}
                {{ render_field(form.description, size=50) }}
                {{ render_field(form.tags, size=50, id="tags") }}
                <tr class="submit">
                    <td></td>
                    <td><button type="submit">Submit</button>
                    </td>
                </tr>
            </table>
        </form>
    </section>
{% endblock %}

{% block sidebar %}
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/vendor/select2.min.js') }}"></script>
<script>
$(document).ready(function(){
    var x = {{ all_tags()|map(attribute='name')|list|tojson }}
    var _tags = {{ all_tags()|map(attribute='name')|list|tojson|safe }};
    console.log(x)
    $('#tags').select2({tags: _tags, tokenSeparators: [",", " "]});
});
</script>
{% endblock %}

thermos/templates/bookmark_list.html
<ul class="bookmarks">
    {% for bookmark in bookmarks %}
        <li>
            {% include "bookmark.html" %}
        </li>
    {% endfor %}
</ul>

thermos/templates/confirm_delete.html
{% extends "base.html" %}

{% block title %}
Thermos -- Delete bookmark
{%  endblock %}

{% block content %}
    <section>
        <h1 style="clear:both">Confirm Delete</h1>

        {% include "bookmark.html" %}


        <form action="" method="post">
            <span style="color:red" >Are you sure you want to delete this bookmark?</span>
            <br><br>
            <a href="{{ url_for('bookmarks.user', username=current_user.username) }}">
                <button type="button">No, take me out of here</button>
            </a>
            <button type="submit">Yes, delete it</button>
        </form>
    </section>
{% endblock %}

{% block sidebar %}
{% endblock %}

thermos/templates/form_macros.html
{% macro render_field(field) %}
    <tr {% if field.errors %} class="error" {% endif %}>
        <td>{{ field.label }}</td>
        <td>{{ field(**kwargs)|safe }}</td>
    </tr>
    <tr class="error" >
        <td></td>
        <td>
            <ul>
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </td>
    </tr>
{% endmacro %}

thermos/templates/index.html
{% extends "base.html" %}

{% block title %}
Thermos -- Welcome
{%  endblock %}

{% block content %}
    <article>
        <header>
            <h1>Welcome</h1>
            <p>Thermos is a simple social bookmarking site. Or actually, it is a demo for the <a href="http://www.pluralsight.com">Pluralsight</a> course titled <em>Flask Fundamentals</em>.</p>
            <p>Don't have an account? Create one by <a href="{{ url_for('auth.signup') }}">Signing up</a></p>
        </header>

        <section>
            <h2>Recently Added</h2>
                {% if new_bookmarks.count() > 0 %}
                    {% with bookmarks=new_bookmarks %}
                        {% include "bookmark_list.html" %}
                    {% endwith %}
                {% else %}
                    No bookmarks have been added yet.
                {% endif %}
        </section>
    </article>
{% endblock %}

thermos/templates/login.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Thermos -- Login
{%  endblock %}

{% block content %}
    <section>
        <h1 style="clear: both">Please login</h1>
        <form action="" method="post">
            {{form.hidden_tag()}}
            <table>
                {{ render_field(form.username, size=50) }}
                {{ render_field(form.password, size=50) }}
                {{ render_field(form.remember_me) }}
                {{ render_field(form.submit) }}
            </table>
        </form>
    </section>
{% endblock %}

{% block sidebar %}
{% endblock %}

thermos/templates/signup.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Thermos -- Login
{%  endblock %}

{% block content %}
    <section>
        <h1 style="clear:both">Create an account</h1>
        <form action="" method="post">
            {{form.hidden_tag()}}
            <table>
                {{ render_field(form.username, size=50) }}
                {{ render_field(form.email, size=50) }}
                {{ render_field(form.password, size=50) }}
                {{ render_field(form.password2, size=50) }}

                <tr class="submit">
                    <td></td>
                    <td><button type="submit">Submit</button>
                    </td>
                </tr>
            </table>
        </form>
    </section>
{% endblock %}

{% block sidebar %}
{% endblock %}

thermos/templates/tag.html
{% extends "base.html" %}

{% block title %}
Thermos -- Bookmarks tagged {{ tag }}
{%  endblock %}

{% block content %}
    <article>
        <header>
            <h1>Bookmarks tagged {{ tag }}</h1>

            {% if tag.bookmarks.count() > 0 %}
                {% with bookmarks = tag.bookmarks %}
                    {% include "bookmark_list.html" %}
                {% endwith %}
            {% else %}
                There are no bookmarks with this tag.
            {% endif %}

        </header>

    </article>
{% endblock %}

thermos/templates/user.html
{% extends "base.html" %}

{% block title %}
Thermos -- Bookmarks for user {{ user.username }}
{%  endblock %}

{% block content %}
    <article>
        <header>
            <h1>Bookmarks for {{ user.username }}</h1>

            {% if user.bookmarks.count() > 0 %}
                {% with bookmarks=user.bookmarks %}
                    {% include "bookmark_list.html" %}
                {% endwith %}
            {% else %}
                <li>This user has not added any bookmarks yet.</li>
            {% endif %}
        </header>

    </article>
{% endblock %}